### PR TITLE
allow serving files from nested asset directories with CORS

### PR DESCRIPTION
**Pull request by sandlerr**
@zendesk/vegemite currently if you have a file like `assets/client/build/index.html` it will 404. Something to do with the `File.join`.

`public_folder` can't be set inside `server.rb` because that is run before we set the `path`.

### CODE REVIEW

**Comment by sandlerr** [comment]
bug seems to be introduced in https://github.com/zendesk/zendesk_apps_tools/pull/127

**Comment by adammw** [comment]
👍

**Comment by ocke** [comment]
👍

**Comment by danielbreves** [comment]
@sandlerr any way we can test this?

**Comment by sandlerr** [comment]
The best way I can think of would be integration tests that run `zat create --v2` followed by `zat server`, create a file in a subdirectory and then curl it. I can work on that later in the week.

**Comment by sandlerr** [comment]
I mean we could just use http://www.sinatrarb.com/testing.html to make a regression test for this specific bug but I don't think it brings as much value.

**Comment by ocke** [comment]
I tried this with @sandlerr try, and it seems to work 👍

**Pull request merged**
