### PR TITLE
Add option for the theme listener to ignore paths specified by the user

### PR DESCRIPTION
**Pull request by jakebellacera**
:v:

/cc @zendesk/vegemite

### Description
The theme listener watches all files in the directory, so when working with a project with a large `node_modules` for instance, this can cause the watcher to perform very slowly. Another issue this solves is that multiple instances of guard can co-exist within the working directory in case you have gulp/webpack watching the `src` folder, for example.

### How it works
Users can specify an `--ignore` option to have the listener explicitly ignore an array of paths. Example:

```
zat theme preview --ignore node_modules src styles
```

### CODE REVIEW

**Comment by jakebellacera** [comment]
:wave: Friendly bump on this. Would you have a moment to check this out?

/cc @ocke @sarmadsangi (and whoever else owns this project)

**Comment by jakebellacera** [comment]
Bumping again.

* * *

Can we update the PR instructions to make sure that outside users can successfully contribute to this open source project? Right now there isn't a way to get the maintainer's attention (see: #281). I would like to get this merged and not have to continue to support my fork as a dependency on our end.

**Comment by ocke** [comment]
Hey @jakebellacera. Sorry for the last response and thanks for the contribution. Do you think we should make zat always ignore `node_modules`. In that case we don't even need to make it a option. Can there be any reason zat should *not* ignore `node_modules`?

**Comment by jakebellacera** [comment]
@ocke no worries!

A default list would be great. I still think the option to configure a manual ignore list will be useful for flexibility!

**Comment by hoangtrvu** [comment]
Hi @jakebellacera, we force updated master branch so can you please rebase your PR? Thank you 🙇

**Comment by sarmadsangi** [comment]
@jakebellacera sorry for missing out on this PR. This is great 🎉

We have seen similar issues with `zat server` as well, so i was thinking if we can tweak this current approach to be a bit more flexible. 

### Suggested solution
1. We have a `.zatignore` with `node_modules`  as default value.
2. Read ignore paths from this file for `zat theme preview` and `zat server`

What do you think?

**Comment by jakebellacera** [comment]
@hoangtrvu updated!

@sarmadsangi the `.zatignore` option would be great!

**Comment by dangayle** [comment]
This would solve my current issue. If you have too many files in your node_modules, Zat will fail with "too many open files" error.

Screen Shot 2019-12-30 at 11 57 44 AM

**Comment by sarmadsangi** [comment]
@augustocravosilva can we get a review and approval from your team for this change?

**Comment by pezholio** [comment]
This would be really good to get in. At the moment I'm blocked from being able to manage my dependencies using Yarn/NPM

**Comment by jakebellacera** [comment]
Bump. Any updates?

**Comment by jakebellacera** [comment]
I'm deciding to close this PR since it doesn't look like it's going to get through. If plans change, I'm happy to reopen.

**Pull request closed without merging**
