### PR TITLE
setting secure settings for zat server is pointless

### PR DESCRIPTION
**Pull request by sandlerr**
cc @zendesk/vegemite

### CODE REVIEW

**Comment by adammw** [comment]
What if app developers use conditional code for when they're running under zat? (have done this myself in a couple of apps...)

**Comment by sandlerr** [comment]
and in that case you have access to those settings?

**Comment by sandlerr** [comment]
not sure, I think it is asking for bugs to make things available only in development. Thoughts on  https://github.com/zendesk/zendesk_app_framework/pull/594 ?

**Comment by ocke** [comment]
👍

**Comment by hoangtrvu** [comment]
Closing due to low activity.

**Pull request closed without merging**
