### PR TITLE
Olaf/local api

### PR DESCRIPTION
**Pull request by ocke**
So I made a little ditty for ZAT that enables apps to write to the local settings!

How swell.

The framework also needs a 1 liner that basically says, if appId===0 then request.url = localhost.
https://github.com/zendesk/zendesk_app_framework/pull/474

/cc @zendesk/quokka
### References
- Jira link: 
### Risks
- None

### CODE REVIEW

**Comment by xuebinglee** [comment]
This looks like a lot of additions. Ideally we would like some tests to cover them.

**Comment by ocke** [comment]
Testing? My code is purfect!

:cat: 

Ok, I will attend to it ;-)

**Comment by ocke** [comment]
@xuebinglee I wrote tests for you.

**Comment by xuebinglee** [comment]
@ocke that's one small step for mankind, one giant leap for Olaf :+1:

**Comment by maximeprades** [comment]
@ocke any plans to merge this now that you are here?

**Comment by ocke** [comment]
@maximeprades yes I am, but it goes together with: https://github.com/zendesk/zendesk_app_framework/pull/474

And we need to get that through too.

**Comment by maximeprades** [comment]
cool

**Comment by sandlerr** [comment]
is this still a thing?

**Pull request closed without merging**
