### PR TITLE
Add default bar app icons

### PR DESCRIPTION
**Pull request by adammw**
:v:

/cc @zendesk/vegemite

### Description

Add default bar app icons

### Risks
* low: too many people submit apps with default icons when they don't need them

### CODE REVIEW

**Comment by sandlerr** [comment]
why? lotus will serve defaults if they're missing

**Comment by adammw** [comment]
Doesn't seem to happen in ZAT, plus it gives devs a base to work off?

**Comment by sandlerr** [comment]
at the cost of making it impossible to change the default later

**Comment by adammw** [comment]
Heh heh... yeah.

**Pull request closed without merging**
