### PR TITLE
[AF-746] Fix default translation files in ZAT

### PR DESCRIPTION
**Pull request by ocke**
:v:

/cc @zendesk/vegemite

### Description
Fix V2 and V1 default translation files.

### References
* JIRA: https://zendesk.atlassian.net/browse/AF-746

### Risks
[low] play button still doesn't work

### CODE REVIEW

**Comment by svizzari** [comment]
What do you think about the idea of somehow using templates and injecting the short_description, installation_instructions, etc. in, so that they're only stored in one place?

**Comment by ocke** [comment]
you mean for v1 and v2, or all the code in general the fact we have it 4 times now.

**Comment by ocke** [comment]
We will get rid of V1 soon anyway, so then that code will be removed.

**Comment by nick-f** [comment]
@svizzari The app_template folder (the v1 template) is going to be removed with [the deprecation warning PR](https://github.com/zendesk/zendesk_apps_tools/pull/190) if there's no objections or other changes required.

**Pull request merged**
