### PR TITLE
Symbol to String bug fixed

### PR DESCRIPTION
**Pull request by ocke**
:koala:

forgot to convert symbol to string in settings helper

/cc @zendesk/quokka

### References
 - Jira link: 

### Risks
 - None

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by xuebingli** [comment]
:+1: on :green_apple:

**Comment by adammw** [comment]
Any chance of adding some regression tests? Or was it a case of the tests stubbing out ZAS and them not being updated?

**Comment by ocke** [comment]
Yeah I fixed the bug and the tests failed because I didn't update the tests. Now I have.

**Pull request merged**
