### PR TITLE
Make app template use the default i18n format as documented

### PR DESCRIPTION
**Pull request by danielbreves**
:bread: 

/cc @zendesk/quokka

### Description
Make app template use the default i18n format as documented [here](https://developer.zendesk.com/apps/docs/agent/i18n).

### References
* HC community: https://support.zendesk.com/hc/en-us/community/posts/209137097-Whats-the-purpose-of-the-package-app-that-messes-with-translations- 

### Risks
* [low] Translations may not work for new apps created using ZAT

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:
should we create a zendesk-specific option for `zat new` to output the non-default?

**Comment by danielbreves** [comment]
@sandlerr https://zendesk.atlassian.net/browse/AF-254

**Comment by svizzari** [comment]
:+1:

**Comment by adammw** [comment]
:+1:

**Pull request merged**
