### PR TITLE
Bump sinatra

### PR DESCRIPTION
**Pull request by ocke**
:koala:

a bug in sinatra, so we need to bump the version.

/cc @zendesk/quokka

### References
 - Jira link: 

### Risks
 - None

### CODE REVIEW

**Comment by sandlerr** [comment]
something to do with routing?
:+1: on green

**Comment by ocke** [comment]
There was a bug in the communication of sinatra and rack. I bumped the sinatra version so it works with our rack version again.

**Comment by danielbreves** [comment]
Any breaking changes from 1.3 to 1.4?

**Comment by danielbreves** [comment]
:+1:

**Comment by ocke** [comment]
not as far as I know, I tested it and the error page works again (like it used to). App.js loads like it should too (and logo.png)

**Pull request merged**
