### PR TITLE
Expose plan information to app developers - allow `--plan=gold` and plan in .zat file

### PR DESCRIPTION
**Pull request by fbvilela**
@zendesk/wombat 

/cc @zendesk/vegemite

### Description
- ZAS bump which exposes the plan information to app developers
- allow plan argument to be passed in zat server and to be put in the .zat file

### References
* JIRA: https://zendesk.atlassian.net/browse/APPS-4597

### Risks
* low - breaks `zat server`

### CODE REVIEW

**Comment by hoangtrvu** [comment]
Hey @fbvilela, we force updated master branch so can you rebase your PR? 🙇

**Comment by fbvilela** [comment]
@hoangtrvu , see if this look ok to you? 
I merged master but I still seem to have a lot of commits as part of this PR. 
the Diff looks good tho... I'm keen to merge

**Comment by Mehul-Porwal** [comment]
@fbvilela Can you rebase instead of merge? That will get rid of all these extra commits.

**Comment by fbvilela** [comment]
Folks I'm ditching this Branch ... 
it was easier to create a new branch from master and apply my commit. 
here it is
https://github.com/zendesk/zendesk_apps_tools/pull/291

**Pull request closed without merging**
