### PR TITLE
version printing

### PR DESCRIPTION
**Pull request by ocke**
:v:

/cc @zendesk/vegemite

### Description
Print the version when doing `zat -v` or `zat --version`

### References
* JIRA: 

### Risks

### CODE REVIEW

**Comment by adammw** [comment]
:+1:

**Comment by sandlerr** [comment]
many gems use a pattern like https://github.com/zendesk/zendesk_api_client_rb/blob/master/lib/zendesk_api/version.rb and reference that constant in the gemspec and anywhere else it is needed. Maybe we can do that?

Also why the double underscore method name?

**Comment by ocke** [comment]
@sandlerr i can use that pattern but does that work with rake bump?

**Comment by sandlerr** [comment]
seems like it: https://github.com/gregorym/bump#supported-locations

**Comment by ocke** [comment]
I removed the underscores, and then it stopped working. I think they mean something special.

**Comment by sandlerr** [comment]
:+1:

**Pull request merged**
